### PR TITLE
Fix #15 Make some Tycho p2 Mojos skippable via Maven CLI

### LINKED ISSUE #15: Make some Tycho p2 Mojos skippable via Maven CLI
I'd like to try your new EditorConfig parser in my new EditorConfig Maven plugin. To do so before you release, I use a source dependency of `org.eclipse.ec4e.services` (via srcdeps [1]). 

However, Tycho p2 plugin does not like the format of srcdeps versions - they are something like `0.1.0.-SRC-revision-3e75ceaea138c6f86231658dbe3d7fced9dfce37` and the plugin complains that `-SRC-revision-3e75ceaea138c6f86231658dbe3d7fced9dfce37` is not a valid qualifier. 

Because actually I do not need any p2 repos, it would be nice if the problematic Tycho plugin executions could be disabled through properties passed as Maven command line parameters. Defaults would of course stay as they are now. 

A PR will follow.

[1] https://github.com/srcdeps/srcdeps-maven#srcdeps-maven

### PR DESCRIPTION
**Pull request by ppalaga**
@angelozerr could you please review?

### CODE REVIEW

**Comment by angelozerr** [comment]
@pascalleclercq could you tell me if it's OK for you please.

**Comment by angelozerr** [comment]
@ppalaga I'm glad that you wish to use the editorconfig parser, but API is perhaps not finalized (even if I think it should not move a lot today), so please take care with that.

Could you add too a `Who is using ec4e` in the README (like https://github.com/eclipse/tm4e/#who-is-using-tm4e) with your project please. Thanks

**Comment by ppalaga** [comment]
@pascalleclercq any hope you'll please find some time to have a look at this?

**Comment by ppalaga** [comment]
Out of date since the parser code moved to https://github.com/angelozerr/ec4j

**Pull request closed without merging**
